// Generated from product/roadmap.json by scripts/render-roadmap.mjs.
// Do not edit this file directly.

export const roadmapRevision = "1.7";
export const roadmapLastReviewed = "2026-07-29";
export const roadmapCurrentHorizon = "H1";
export const roadmap = [
  {
    "id": "H0",
    "title": "Product foundation",
    "status": "Complete",
    "progress": 100,
    "outcome": "A coherent product shell with stable contracts, deterministic replay, and clean Windows/Linux build gates.",
    "now": [
      "Product language and interactive preview",
      "Typed provider boundary",
      "Product specification and architecture"
    ],
    "gates": [
      "The Svelte interface contains no provider transport or orchestration business logic.",
      "The Rust core runs in tests without Tauri.",
      "A recorded fake session replays into the complete task interface."
    ]
  },
  {
    "id": "H1",
    "title": "Connected vertical slice",
    "status": "In progress",
    "progress": 88,
    "outcome": "One genuine repository task completes safely through each required provider type.",
    "now": [
      "Provider-driven repository task loop"
    ],
    "gates": [
      "The same fixture task completes through OpenAI, Anthropic, and a local compatible server.",
      "Tool input and results appear in causal order.",
      "Cancellation stops generation and execution within a documented bound."
    ]
  },
  {
    "id": "H2",
    "title": "Reliable task workspace",
    "status": "Planned",
    "progress": 0,
    "outcome": "Kiln supports concurrent daily work that survives restarts and preserves user changes.",
    "now": [
      "Per-task Git worktrees and branches",
      "Concurrent task supervision",
      "Checkpoints, retry, fork, and targeted restore"
    ],
    "gates": [
      "Two tasks can change one repository without sharing workspace or event state.",
      "Restart during a turn produces a truthful recoverable task.",
      "Restoring one checkpoint preserves unrelated user work."
    ]
  },
  {
    "id": "H3",
    "title": "Open agent ecosystem",
    "status": "Planned",
    "progress": 0,
    "outcome": "Existing agents and external tools operate through Kiln's task, event, and permission surfaces.",
    "now": [
      "MCP stdio and HTTP clients",
      "ACP client and capability negotiation",
      "Goose and OpenCode profiles"
    ],
    "gates": [
      "Goose and OpenCode sessions run through the same task interface.",
      "Unsupported capabilities disable with an explanation.",
      "MCP tools pass through the central permission engine."
    ]
  },
  {
    "id": "H4",
    "title": "Windows and Linux beta",
    "status": "Planned",
    "progress": 0,
    "outcome": "A polished, installable daily driver for regular personal use.",
    "now": [
      "Installers, signing, and safe updates",
      "Keyboard, accessibility, and reduced motion",
      "Long-session performance and diagnostics"
    ],
    "gates": [
      "All core flows are keyboard accessible.",
      "A 10,000-event session meets the agreed responsiveness budget.",
      "A 24-hour task leaks neither processes nor unbounded memory."
    ]
  },
  {
    "id": "H5",
    "title": "Secure autonomy and remote operation",
    "status": "Deferred",
    "progress": 0,
    "outcome": "Long-running tasks gain stronger containment and remote supervision without weakening the local trust model.",
    "now": [
      "Platform process and filesystem containment",
      "Headless daemon and authenticated pairing"
    ],
    "gates": [
      "Filesystem, network, CPU, memory, and execution-time limits are enforced and visible.",
      "Remote pairing expires, revokes, and reconnects safely.",
      "Security documentation distinguishes guarantees from best-effort controls."
    ]
  },
  {
    "id": "H6",
    "title": "macOS release",
    "status": "Later",
    "progress": 0,
    "outcome": "Supported daily-driver workflows reach signed and notarized macOS parity.",
    "now": [
      "Native macOS platform adapter and packaging"
    ],
    "gates": [
      "Provider, Git, terminal, permission, credential, update, and recovery suites pass.",
      "Packages are signed and notarized.",
      "Apple Silicon is verified on physical hardware."
    ]
  },
  {
    "id": "H7",
    "title": "Advanced orchestration",
    "status": "Discovery",
    "progress": 0,
    "outcome": "Kiln differentiates through understandable, policy-aware coordination rather than agent count.",
    "now": [
      "Parallel specialist task graphs",
      "Model comparison and evaluation fixtures",
      "Reusable recipes and policy-aware review"
    ],
    "gates": [
      "Every candidate has a user problem, success measure, and security model before commitment."
    ]
  }
] as const;
