// Generated from product/roadmap.json by scripts/render-roadmap.mjs.
// Do not edit this file directly.

export type RoadmapLane = "now" | "next" | "later";

export interface RoadmapPhase {
  id: string;
  title: string;
  horizon: string;
  status: RoadmapLane;
  summary: string;
  outcomes: readonly string[];
}

export const roadmapRevision = "1.8";
export const roadmapLastReviewed = "2026-07-29";
export const roadmapCurrentHorizon = "H1";
export const roadmap: readonly RoadmapPhase[] = [
  {
    "id": "H0",
    "title": "Product foundation",
    "horizon": "Current",
    "status": "now",
    "summary": "A coherent product shell with stable contracts, deterministic replay, and clean Windows/Linux build gates.",
    "outcomes": [
      "Product language and interactive preview",
      "Typed provider boundary",
      "Product specification and architecture"
    ]
  },
  {
    "id": "H1",
    "title": "Connected vertical slice",
    "horizon": "Parallel with H0 infrastructure gates",
    "status": "now",
    "summary": "One genuine repository task completes safely through each required provider type.",
    "outcomes": [
      "Provider-driven repository task loop"
    ]
  },
  {
    "id": "H2",
    "title": "Reliable task workspace",
    "horizon": "After the H1 slice",
    "status": "next",
    "summary": "Kiln supports concurrent daily work that survives restarts and preserves user changes.",
    "outcomes": [
      "Per-task Git worktrees and branches",
      "Concurrent task supervision",
      "Checkpoints, retry, fork, and targeted restore"
    ]
  },
  {
    "id": "H3",
    "title": "Open agent ecosystem",
    "horizon": "After workspace reliability",
    "status": "later",
    "summary": "Existing agents and external tools operate through Kiln's task, event, and permission surfaces.",
    "outcomes": [
      "MCP stdio and HTTP clients",
      "ACP client and capability negotiation",
      "Goose and OpenCode profiles"
    ]
  },
  {
    "id": "H4",
    "title": "Windows and Linux beta",
    "horizon": "After ecosystem hardening",
    "status": "later",
    "summary": "A polished, installable daily driver for regular personal use.",
    "outcomes": [
      "Installers, signing, and safe updates",
      "Keyboard, accessibility, and reduced motion",
      "Long-session performance and diagnostics"
    ]
  },
  {
    "id": "H5",
    "title": "Secure autonomy and remote operation",
    "horizon": "Deferred until the local product is stable",
    "status": "later",
    "summary": "Long-running tasks gain stronger containment and remote supervision without weakening the local trust model.",
    "outcomes": [
      "Platform process and filesystem containment",
      "Headless daemon and authenticated pairing"
    ]
  },
  {
    "id": "H6",
    "title": "macOS release",
    "horizon": "After launch-platform parity",
    "status": "later",
    "summary": "Supported daily-driver workflows reach signed and notarized macOS parity.",
    "outcomes": [
      "Native macOS platform adapter and packaging"
    ]
  },
  {
    "id": "H7",
    "title": "Advanced orchestration",
    "horizon": "Exploratory",
    "status": "later",
    "summary": "Kiln differentiates through understandable, policy-aware coordination rather than agent count.",
    "outcomes": [
      "Parallel specialist task graphs",
      "Model comparison and evaluation fixtures",
      "Reusable recipes and policy-aware review"
    ]
  }
];
